<script type="text/x-magento-init">
{
    ".gallery-slider": {
        "slick": {
            "slidesToShow": 2,
            "dots": true,
            "infinite": true,
            "dotsClass": "bannerSliderButton",
            "responsive": [
            {
              "breakpoint": 768,
              "settings": {
                "slidesToShow": 1
              }
            }
          ]
        }
    }
}
</script>