<!--<script>-->
<!--    require([-->
<!--        'jquery',-->
<!--        'slick',-->
<!--        'domReady!'-->
<!--    ], function ($) {-->
<!--        $.widget($(".banner-container").slick({-->
<!--            dots: true,-->
<!--            infinite: true,-->
<!--            speed: 300,-->
<!--            slidesToShow: 1,-->
<!--            slidesToScroll: 1-->
<!--        }))-->
<!--    })-->
<!--</script>-->

<script type="text/x-magento-init">
{
    ".banner-container": {
        "slick": {
            "slidesToShow": 1,
            "dots": true,
            "infinite": true
        }
    }
}
</script>
