<script type="text/x-magento-init">
{
    "#brand-slider": {
        "slick": {
            "slidesToShow": 5,
            "slidesToScroll": 2,
            "dots": true,
            "dotsClass": "bannerSliderButton",
            "infinite": false,
            "responsive": [
            {
              "breakpoint": 980,
              "settings": {
                "slidesToShow": 4,
                "slidesToScroll": 2
              }
            },
            {
              "breakpoint": 768,
              "settings": {
                "slidesToShow": 3,
                "slidesToScroll": 2
              }
            },
            {
              "breakpoint": 480,
              "settings": {
                "slidesToShow": 2,
                "slidesToScroll": 1
              }
            }
          ]
        }
    }
}
</script>
