<script type="text/x-magento-init">
{
  ".products-row .product-items": {
    "slick": {
      "slidesToShow": 4,
      "slidesToScroll": 4,
      "infinite": false,
      "responsive": [
        {
          "breakpoint": 980,
          "settings": {
            "slidesToShow": 3,
            "slidesToScroll": 3
          }
        },
        {
          "breakpoint": 768,
          "settings": {
            "slidesToShow": 2,
            "slidesToScroll": 2
          }
        },
        {
          "breakpoint": 480,
          "settings": {
            "slidesToShow": 1,
            "slidesToScroll": 1
          }
        }
      ]
    }
  }
}
</script>
