
<script type="text/x-magento-init">
{
    ".news-block": {
        "slick": {
            "slidesToShow": 3,
            "infinite": true,
            "responsive": [
        {
          "breakpoint": 768,
          "settings": {
            "slidesToShow": 2,
            "slidesToScroll": 2
          }
        },
        {
          "breakpoint": 480,
          "settings": {
            "slidesToShow": 1,
            "slidesToScroll": 1
          }
        }
      ]
        }
    }
}
</script>
