<?php
/**
 * @var $block \Mirasvit\Giftr\Block\Item\Add
 */
?>

<div class="giftr-list" style="display: none"
     data-bind="scope: 'giftr-addto__form'"
     data-mage-init='{"GiftrWindow" : {}}'>
    <div class="registry-list" data-bind="visible: hasRegistries">
        <h3>Select Gift Registry</h3>
        <select class="registries"
                data-bind="options: registries, optionsText: 'label', optionsValue: 'value', value: selected">
        </select>
        <button class="action primary modal-btn " id="confirm-add-to-registry" href="#" data-bind="click: addProduct"><?= __('Add') ?></button>
    </div>

    <div data-bind="visible: isMessageVisible()">
        <span data-bind="html: getMessage()"></span>
    </div>
</div>