<?php
/**
 * @var $block \Mirasvit\Giftr\Block\Item\Add
 */
?>

<div class="giftr-list" style="display: none"
     data-bind="scope: 'giftr-addto__form'"
     data-mage-init='{"dropdownDialog":{
                "appendTo":".add-to-giftr",
                "triggerTarget":".togiftr",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "defaultDialogClass":"giftr-dropdown",
                "show":{
                    "effect":"fade",
                    "duration": 200
                },
                "hide":{
                    "effect":"fade",
                    "duration": 200
                },
                "buttons":[]}}'>



    <div class="registry-list" data-bind="visible: hasRegistries">
        <h3>Select Gift Registry</h3>
        <select class="registries"
                data-bind="options: registries, optionsText: 'label'">
        </select>
        <button id="confirm-add-to-registry" href="#" data-bind="click: addProduct"><?= __('Add') ?></button>
    </div>

    <div data-bind="visible: isMessageVisible()">
        <span data-bind="html: getMessage()"></span>
    </div>
</div>