<div class="container">
    <h1 class="gallery-title">Gallery</h1>
</div>
<div class="container gallery-slider">
    <img src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/blog/images/0/9/09_4.jpg" alt="">
    <img src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/blog/images/0/4/04_4.jpg" alt="">
    <img src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/blog/images/0/3/03_4.jpg" alt="">
    <img src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/blog/images/0/5/05_3.jpg" alt="">
</div>